name: flutter_lib
description: A new flutter module project.
version: 1.0.0+1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_boost: 0.1.61
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  module:
    androidX: false
    androidPackage: com.example.flutter_lib
    iosBundleIdentifier: com.example.flutterLib
